### ISSUE TITLE
What needs to be changed if I my training script depends on other scripts too?

### ISSUE THREAD

**Issue by mshseek** [aws-samples/amazon-sagemaker-script-mode#1]
In the example, [train.py](https://github.com/aws-samples/amazon-sagemaker-script-mode/blob/master/tf-eager-script-mode/train.py) contains all the logic to get training data, build the model, train and evaluate.

How would this example change if `train.py` depends on multiple modules?  For example, I have the model definition logic stored in a separate file called `model.py`.

**Comment by rabowskyb** [comment]
Hello, to use multiple source files, you need to use the source_dir argument when setting up the Estimator, and then put your code files in the directory you specify.  I've modified the Text Classification example in this repo to show this functionality, see https://github.com/aws-samples/amazon-sagemaker-script-mode/tree/master/keras-embeddings-script-mode.
