### ISSUE TITLE
"Error: argument "agent" is wrong: table id value is invalid" Error

### ISSUE THREAD

**Issue by rsandler00** [aws-samples/amazon-sagemaker-script-mode#15]
Hi, 

I am trying to run the `tf-2-workflow/tf-2-workflow.ipynb` notebook. I was able to get it to run until I reach the line `!/bin/bash ./local_mode_setup.sh`. Then I get the following errors:

```
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/networks: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/networks/create: dial unix /var/run/docker.sock: connect: permission denied
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get http://%2Fvar%2Frun%2Fdocker.sock/v1.40/networks: dial unix /var/run/docker.sock: connect: permission denied
Error: argument "agent" is wrong: table id value is invalid
```

I fixed my Docker permissions w/ this guide [here](https://medium.com/@dhananjay4058/solving-docker-permission-denied-while-trying-to-connect-to-the-docker-daemon-socket-2e53cccffbaa), so I am able to successfully run `docker run hello-world`. The issue seems to be with the following line in `local_mode_setup.sh`:

`ROUTE_TABLE_PATCHED=`sudo ip route show table agent | grep -c $SAGEMAKER_INTERFACE``

Please help. Thanks!

**Comment by rabowskyb** [comment]
Hello, I just tried to reproduce by creating a fresh, brand new SageMaker notebook instance and then running that notebook.  However, I did not encounter that error.

Are you using a SageMaker Notebook Instance?  Or SageMaker Studio?  Or an EC2 instance or something else?  The Local Mode portion of the notebook is meant to run on SageMaker Notebook Instances only, I will add a comment in that notebook to that effect.

**Comment by rsandler00** [comment]
Hi @rabowskyb , 

Thanks for the response. I am actually using a free-tier Ubuntu 18 instance. Is it expected to work there? If not, is there anyway to learn about and try SageMaker on a small scale for free?

**Comment by rabowskyb** [comment]
Yes, there is a SageMaker free tier:  see https://aws.amazon.com/sagemaker/pricing/.  You should be able to run the notebook on a free tier t3 or t2 SageMaker notebook instance.  Then for the rest of the notebook, change the training type from c5 to m5.xlarge.  

That should resolve this issue, so I'll close it for now; if you run into other errors, please let us know (btw I modified the notebook to warn about notebook choice and update to SDK v2; you probably will want to pull the new version).
