### ISSUE TITLE
Comparison statement instead of assignment operation in `save_history` function

### ISSUE THREAD

**Issue by vforvoid** [aws-samples/amazon-sagemaker-script-mode#16]
Several TF related examples contain a `save_history` with the following statements:

https://github.com/aws-samples/amazon-sagemaker-script-mode/blob/e22f8433ee36a015381292f043d56417d4fabd5c/tf-batch-inference-script/code/train.py#L38-L39

I believe you wanted to use assignment instead of comparison here.

**Comment by rabowskyb** [comment]
Thanks for pointing this out -- it has now been corrected.
