### ISSUE TITLE
get an error message of no module named transformer for deploy-pretrained-model/BERT/Deploy_BERT.ipynb

### ISSUE THREAD

**Issue by teressakim70** [aws-samples/amazon-sagemaker-script-mode#17]
Hi 

I read your deploy bert notebook and followed the steps (made changes to use distilbert rather bert) and created endpoint and I can see that
from dashboard it has inservice status

However when I tried to endpoint using your example code,

import boto3

sm = boto3.client('sagemaker-runtime')

prompt = "The best part of Amazon SageMaker is that it makes machine learning easy."

response = sm.invoke_endpoint(EndpointName=endpoint_name, 
                              Body=prompt.encode(encoding='UTF-8'),
                              ContentType='text/csv')

response['Body'].read()

I get an error message of no module named transformer.

ModelError                                Traceback (most recent call last)
<ipython-input-4-154e43bc8826> in <module>
      6 response = sm.invoke_endpoint(EndpointName=endpoint_name, 
      7                               Body=prompt.encode(encoding='UTF-8'),
----> 8                               ContentType='text/csv')
      9 
     10 response['Body'].read()

/opt/conda/lib/python3.7/site-packages/botocore/client.py in _api_call(self, *args, **kwargs)
    355                     "%s() only accepts keyword arguments." % py_operation_name)
    356             # The "self" in this scope is referring to the BaseClient.
--> 357             return self._make_api_call(operation_name, kwargs)
    358 
    359         _api_call.__name__ = str(py_operation_name)

/opt/conda/lib/python3.7/site-packages/botocore/client.py in _make_api_call(self, operation_name, api_params)
    674             error_code = parsed_response.get("Error", {}).get("Code")
    675             error_class = self.exceptions.from_code(error_code)
--> 676             raise error_class(parsed_response, operation_name)
    677         else:
    678             return parsed_response

ModelError: An error occurred (ModelError) when calling the InvokeEndpoint operation: Received server error (500) from model with message "No module named 'transformers'
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_inference/transformer.py", line 110, in transform
    self.validate_and_initialize(model_dir=model_dir)
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_inference/transformer.py", line 157, in validate_and_initialize
    self._validate_user_module_and_set_functions()
  File "/opt/conda/lib/python3.6/site-packages/sagemaker_inference/transformer.py", line 170, in _validate_user_module_and_set_functions
    user_module = importlib.import_module(user_module_name)
  File "/opt/conda/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/ml/model/code/deploy_distilbert.py", line 12, in <module>
    from transformers import DistilBertTokenizer, DistilBertForTokenClassification
ModuleNotFoundError: No module named 'transformers'
". See https://eu-west-2.console.aws.amazon.com/cloudwatch/home?region=eu-west-2#logEventViewer:group=/aws/sagemaker/Endpoints/distilbert-base-cased in account 645532039181 for more information.

I am having terrible time of understanding how to use pre-trained model in sagemaker and would really appreciate if you could help.

In the log, it says:

Python executable: /opt/conda/bin/python 

And I checked the python and it does have transfomers module installed

# /opt/conda/bin/python
Python 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import transformers
>>> quit()

My requirements.txt has:

transformers>=4.0.0
tensorflow==1.13.1
torch==1.5.0

When I run this cell, I added requirements.txt into code, 
import tarfile

zipped_model_path = os.path.join(model_path, "model.tar.gz")

with tarfile.open(zipped_model_path, "w:gz") as tar:
    tar.add(model_path)
    tar.add(code_path)

Would you please tell me what's going wrong?

Thanks
Teresa

**Comment by swlkn** [comment]
Hi Teresa,

thank you for trying the notebook. I'm sorry that you are having problems. I tried replacing the body of requirements.txt with the following:

```
transformers>=4.0.0
tensorflow==1.13.1
torch==1.5.0
```

And it worked on my laptop. I didn't change the model from bert base to distilbert however. It's important to note that creating a SageMaker endpoint creates a separate compute instance from the environment you execute this notebook. So even if transformers is installed on the local notebook, it needs to be installed on the endpoint as well (which the requirements.txt should handle). I recommend changing the line in the notebook that installs the transformers library to install 4.0.0 like this:

`!pip install transformers==4.0.0 sagemaker==2.15.0 --quiet`

 You may also consider [SageMaker JumpStart](https://aws.amazon.com/blogs/aws/amazon-sagemaker-jumpstart-simplifies-access-to-prebuilt-models-and-machine-learning-models/), which is a new feature which helps customers get started with SageMaker. You can browse model zoos and quickly deploy popular models (like distilbert). 
 
 Best,
 
 Sean

**Comment by rabowskyb** [comment]
Hello, we will assume that this issue is now resolved.  If you experience further difficulties, please feel free to re-open this issue.
