### ISSUE TITLE
 aws-samples / amazon-sagemaker-script-mode / tf-2-workflow preprocessing.py bug

### ISSUE THREAD

**Issue by frgud** [aws-samples/amazon-sagemaker-script-mode#21]
When running the preprocessing.py script as part of the `sklearn_processor.run` step of the notebook, the SageMaker Processing job fails with an "Algorithm" error.  The CloudWatch logs show the following:

> 2021-07-09T17:12:14.418-04:00 | INPUT FILE List
> 2021-07-09T17:12:14.418-04:00 | ['/opt/ml/processing/input/x_test.npy', '/opt/ml/processing/input/y_test.npy']
> 2021-07-09T17:12:14.418-04:00 | SAVED TRANSFORMED TEST DATA FILE
> 2021-07-09T17:12:14.418-04:00
> Traceback (most recent call last):
>   File "/opt/ml/processing/input/code/preprocessing.py", line 14, in <module>
>     transformed = scaler.fit_transform(raw)
>   File "/miniconda3/lib/python3.7/site-packages/sklearn/base.py", line 462, in fit_transform
>     return self.fit(X, **fit_params).transform(X)
>   File "/miniconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py", line 617, in fit
>     return self.partial_fit(X, y)
>   File "/miniconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py", line 641, in partial_fit
>     force_all_finite='allow-nan')
>   File "/miniconda3/lib/python3.7/site-packages/sklearn/utils/validation.py", line 547, in check_array
>     "if it contains a single sample.".format(array))
> 2021-07-09T17:12:14.418-04:00
> ValueError: Expected 2D array, got 1D array instead:
> 2021-07-09T17:12:14.418-04:00
> array=[ 7.2 18.8 19.  27.  22.2 24.5 31.2 22.9 20.5 23.2 18.6 14.5 17.8 50.
>  20.8 24.3 24.2 19.8 19.1 22.7 12.  10.2 20.  18.5 20.9 23.  27.5 30.1
>   9.5 22.  21.2 14.1 33.1 23.4 20.1  7.4 15.4 23.8 20.1 24.5 33.  28.4
>  14.1 46.7 32.5 29.6 28.4 19.8 20.2 25.  35.4 20.3  9.7 14.5 34.9 26.6
>   7.2 50.  32.4 21.6 29.8 13.1 27.5 21.2 23.1 21.9 13.  23.2  8.1  5.6
>  21.7 29.6 19.6  7.  26.4 18.9 20.9 28.1 35.4 10.2 24.3 43.1 17.6 15.4
>  16.2 27.1 21.4 21.5 22.4 25.  16.6 18.6 22.  42.8 35.1 21.5 36.  21.9
>  24.1 50.  26.7 25. ].
> 2021-07-09T17:12:14.418-04:00
> Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

Adding the `array.reshape()` recommendation is misleading and does not fix the problem.

I have found a working solution by changing the third cell (which generates the preprocessing.py script that throws the above error) to the following:

`python3
%%writefile preprocessing.py

import glob
import numpy as np
import os
from sklearn.preprocessing import StandardScaler

if __name__=='__main__':
    
    input_files = glob.glob('{}/*.npy'.format('/opt/ml/processing/input'))
    print('\nINPUT FILE LIST: \n{}\n'.format(input_files))
    scaler = StandardScaler()
    for file in input_files:
        if 'x_' in file:
            X = file
        elif 'y_' in file:
            y = file
    raw_x = np.load(X)
    raw_y = np.load(y)
    transformed = scaler.fit_transform(raw_x, raw_y)
    if 'train' in file:
        output_path = os.path.join('/opt/ml/processing/train', 'x_train.npy')
        np.save(output_path, transformed)
        print('SAVED TRANSFORMED TRAINING DATA FILE\n')
    else:
        output_path = os.path.join('/opt/ml/processing/test', 'x_test.npy')
        np.save(output_path, transformed)
        print('SAVED TRANSFORMED TEST DATA FILE\n')
` 

This change allows `fit_transform` to build the transformed data set while being aware of the dimensionality of the y predictions.  This removes the error in training and allows the model to be trained and deployed locally or on a hosted endpoint and to generate inferences.

I don't know if this is the best solution, but it's one that fixes the error with this notebook.

**Comment by rabowskyb** [comment]
Hi @frgud thanks for noticing this, I will merge in your related PR.  BTW, please note that this notebook generally has been superseded by the workflow notebook with SageMaker Pipelines, which is the one we generally update.  It uses a more recent version of sklearn that does not raise this exception.  The link is:  https://github.com/aws-samples/amazon-sagemaker-script-mode/blob/master/tf-2-workflow-smpipelines/tf-2-workflow-smpipelines.ipynb
