### ISSUE TITLE
Typo alert: use assignment (=) instead of comparison (==).

### ISSUE THREAD

**Issue by mmilosav** [aws-samples/amazon-sagemaker-script-mode#26]
https://github.com/aws-samples/amazon-sagemaker-script-mode/blob/4452cbd09ae46b28d5a270846fc17fafc5509a63/tf-sentiment-script-mode/sentiment.py#L42

**Comment by rabowskyb** [comment]
Thanks for pointing this out -- this issue has been corrected by merging PR #27.
