### ISSUE TITLE
Need to define model_dir in tf-2-word-embeddings example

### ISSUE THREAD

**Issue by nahidalam** [aws-samples/amazon-sagemaker-script-mode#30]
In the `tf-2-word-embeddings` the variable `model_dir` is not defined https://github.com/aws-samples/amazon-sagemaker-script-mode/blob/master/tf-2-word-embeddings/tf-2-word-embeddings.ipynb

Am I missing something?

**Comment by rabowskyb** [comment]
Hello -- good question -- yes, that parameter isn't defined.   The best practice here is just to leave out that parameter, if you refer to the training script, the model directory is just the SageMaker default, which is defined by a SageMaker environment variable.  https://github.com/aws-samples/amazon-sagemaker-script-mode/blob/7f4feeea50b0e7a5b35291d0991c3cfa7ba11be6/tf-2-word-embeddings/code/train.py#L32

For an updated example of a TensorFlow estimator config, see https://github.com/aws-samples/amazon-sagemaker-script-mode/blob/master/tf-2-workflow-smpipelines/tf-2-workflow-smpipelines.ipynb.

I'll close this issue for now, please re-open if the example isn't working.  Cleanup of the code will occur at a later date.
