### ISSUE TITLE
Replace global reference with a local variable in example script

### ISSUE THREAD

**Issue by i-zaitsev** [aws-samples/amazon-sagemaker-script-mode#5]
[There is a function](https://github.com/aws-samples/amazon-sagemaker-script-mode/blob/e68b209fa3c3e286df72ec839addc26bb4988526/tf-distribution-options/code/train_ps.py#L50) in one of the SageMaker's examples that saves Keras model onto disk:
```python
def save_model(model, output):
    tf.contrib.saved_model.save_keras_model(model, args.model_dir)
    logging.info("Model successfully saved at: {}".format(output))
    return
```
But it seems that the function doesn't use `output` variable and refers global `args.model_dir` instead. 

How do you think, should this function be replaced with something like this?
```python
def save_model(model, output):
    tf.contrib.saved_model.save_keras_model(model, output)
    logging.info("Model successfully saved at: {}".format(output))
```

**Comment by rabowskyb** [comment]
Yes, agreed the function should be modified along those lines.  Thanks for pointing this out!
