### ISSUE TITLE
How do I set up Ubuntu based docker for Sagemaker Local mode training?

### ISSUE THREAD

**Issue by giriannamalai** [aws-samples/amazon-sagemaker-script-mode#7]
I'm having Ubuntu 16.04 with Nvidia support. The setup.sh available in keras script mode for CNN Text classification. Can't run install local mode training container in Ubuntu?

**Comment by rabowskyb** [comment]
Script Mode only uses a set of prebuilt containers provided by AWS for Local Mode.
