### ISSUE TITLE
[Error] Notebook: sentiment-analysis.ipynb in SageMaker Studio with kernel Python3 (Tensorflow2 GPU Optimized)

### ISSUE THREAD

**Issue by gonsoomoon-ml** [aws-samples/amazon-sagemaker-script-mode#9]
Hello,
When I ran the following condition and code, I had an error.
I appreciate if you provide some suggestions.

Thanks.

 notebook:
   - sentiment-analysis.ipynb
 Env:
   - SageMaker Studio
 Kernel
   - Python3 (Tensorflow2 GPU Optimized)
 Code:
!wget -q https://raw.githubusercontent.com/aws-samples/amazon-sagemaker-script-mode/master/local_mode_setup.sh
!wget -q https://raw.githubusercontent.com/aws-samples/amazon-sagemaker-script-mode/master/daemon.json    
! /bin/bash ./local_mode_setup.sh

 Error:
./local_mode_setup.sh: line 7: rpm: command not found
./local_mode_setup.sh: line 10: yum: command not found
./local_mode_setup.sh: line 12: [: -eq: unary operator expected
./local_mode_setup.sh: line 20: sudo: command not found
./local_mode_setup.sh: line 21: sudo: command not found
./local_mode_setup.sh: line 23: sudo: command not found
./local_mode_setup.sh: line 25: sudo: command not found
(23) Failed writing body
./local_mode_setup.sh: line 26: sudo: command not found
./local_mode_setup.sh: line 27: sudo: command not found
./local_mode_setup.sh: line 28: sudo: command not found
installed nvidia-docker2
./local_mode_setup.sh: line 45: docker: command not found
./local_mode_setup.sh: line 47: docker: command not found
./local_mode_setup.sh: line 51: sudo: command not found
./local_mode_setup.sh: line 54: docker: command not found
./local_mode_setup.sh: line 55: ip: command not found
./local_mode_setup.sh: line 56: ip: command not found
./local_mode_setup.sh: line 59: sudo: command not found
./local_mode_setup.sh: line 60: sudo: command not found

**Comment by rabowskyb** [comment]
Hello, thank you for raising this issue!  SageMaker Studio currently does not support Docker and as a result, it also does not support Local Mode.  Many apologies for the inconvenience!  I have requested support for Docker in Studio, but in the meantime, please run the example outside Studio either in classic SageMaker Notebook Instances or any other platform that supports Docker.  Thanks!
